In [1]:
import pandas as pd
import numpy as np
import json

with open('cleaned_jobs_data.json', 'r') as f:
    data = json.load(f)
df = pd.DataFrame(data)
print(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 12519 entries, 0 to 12518
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   post_id             12519 non-null  str
 1   company_name        12519 non-null  str
 2   job_name            12519 non-null  str
 3   skills              12519 non-null  str
 4   date_scraped        12519 non-null  str
 5   date_posted         12519 non-null  str
 6   actual_date_posted  12519 non-null  str
 7   tech_name           12519 non-null  str
 8   tech_category       12519 non-null  str
 9   base_language       12519 non-null  str
dtypes: str(10)
memory usage: 978.2 KB
None

,post_id,company_name,job_name,skills,date_scraped,date_posted,actual_date_posted,tech_name,tech_category,base_language
0,GLOBINVA,"Global Infotek, Inc.",Lead Engineer - Legacy Software Baseline - POK...,GitLab,2026-02-12T00:00:00.000,1 day ago,2026-02-11T00:00:00.000,GITLAB,Cloud & Infra,None
1,GLOBINVA,"Global Infotek, Inc.",Lead Engineer - Legacy Software Baseline - POK...,Amazon Web Services,2026-02-12T00:00:00.000,1 day ago,2026-02-11T00:00:00.000,AMAZON WEB SERVICES,Cloud & Infra,None
2,GLOBINVA,"Global Infotek, Inc.",Lead Engineer - Legacy Software Baseline - POK...,Microsoft Azure,2026-02-12T00:00:00.000,1 day ago,2026-02-11T00:00:00.000,AZURE,Cloud & Infra,None
3,GLOBINVA,"Global Infotek, Inc.",Lead Engineer - Legacy Software Baseline - POK...,Microsoft Azure,2026-02-12T00:00:00.000,1 day ago,2026-02-11T00:00:00.000,MICROSOFT AZURE,Cloud & Infra,None
4,GLOBINVA,"Global Infotek, Inc.",Cloud Engineer - Lead BBPO 1642,Google Cloud Platform,2026-02-12T00:00:00.000,1 day ago,2026-02-11T00:00:00.000,GOOGLE CLOUD PLATFORM,Cloud & Infra,None

In [2]:
from sqlalchemy import create_engine
import dotenv
dotenv.load_dotenv()

# 1. เชื่อมต่อกับฐานข้อมูล
# เปลี่ยน user, password, host, port, db_name ให้ตรงกับของคุณ
engine = create_engine(f'postgresql://postgres:{dotenv.dotenv_values().get("PASSWORD")}@localhost:5432/{dotenv.dotenv_values().get("DB_NAME")}')

company Insert

In [3]:
df_company = df[['company_name']].drop_duplicates(keep='first').reset_index(drop=True)
df_company.rename(columns={'company_name': 'companyname'}, inplace=True)
print(df_company.info())
display(df_company.head())

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   companyname  125 non-null    str
dtypes: str(1)
memory usage: 1.1 KB
None

                              companyname
0                    Global Infotek, Inc.
1  BlueCross BlueShield Of South Carolina
2                 BURGEON IT SERVICES LLC
3                    REDLEO SOFTWARE INC.
4                         Infomerica, Inc

In [4]:
df_company.to_sql('company', engine, if_exists='append', index=False)

125

job Insert

In [4]:
df_job = df[['job_name', 'company_name', 'actual_date_posted']].copy()
df_job['actual_date_posted'] = pd.to_datetime(df_job['actual_date_posted'], errors='coerce').dt.year
df_company_id = pd.read_sql('SELECT * FROM company', engine)
df_job = df_job.merge(df_company_id, left_on='company_name', right_on='companyname', how='left')
df_job.drop(columns=['company_name', 'companyname'], inplace=True)
df_job.drop_duplicates(inplace=True)
df_job.rename(columns={'job_name': 'jobname', 'actual_date_posted': 'year'}, inplace=True)
df_job.reset_index(drop=True, inplace=True)
print(df_job.info())
display(df_job.head())

<class 'pandas.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobname    1645 non-null   str
 1   year       1645 non-null   int32
 2   companyid  1645 non-null   int64
dtypes: int32(1), int64(1), str(1)
memory usage: 32.3 KB
None

                                             jobname  year  companyid
0  Lead Engineer - Legacy Software Baseline - POK...  2026          1
1                    Cloud Engineer - Lead BBPO 1642  2026          1
2                     Cloud Engineer - Mid BBPO 1640  2026          1
3                  Cloud Engineer - Senior BBPO 1641  2026          1
4      Interactive On-Net Operator (ION) - JBMD 1633  2026          1

In [10]:
df_job.to_sql('job', engine, if_exists='append', index=False)

645

job_from_source Insert

In [5]:
df_job = pd.read_sql('SELECT * FROM job', engine)
df_job['sourceid'] = 1
df_job_from_source = df_job[['jobid', 'sourceid']].copy()
df_job_from_source.drop_duplicates(inplace=True)
print(df_job_from_source.info())
display(df_job_from_source.head())

<class 'pandas.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   jobid     1645 non-null   int64
 1   sourceid  1645 non-null   int64
dtypes: int64(2)
memory usage: 25.8 KB
None

   jobid  sourceid
0      1         1
1      2         1
2      3         1
3      4         1
4      5         1

In [17]:
df_job_from_source.to_sql('job_from_source', engine, if_exists='append', index=False)

645

job_prolang Insert

In [27]:
df_prolang = pd.read_sql('SELECT * FROM prolang', engine)
df_job_skill = df[['job_name', 'tech_name','base_language']].copy()
df_job_skill.drop_duplicates(inplace=True)
df_job_skill.loc[df_job_skill['base_language'] == 'None', 'base_language'] = np.nan
print(df_prolang.info())
print(df_job_skill.info())

<class 'pandas.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   prolangid    59 non-null     int64
 1   prolangname  59 non-null     str
dtypes: int64(1), str(1)
memory usage: 1.1 KB
None
<class 'pandas.DataFrame'>
Index: 7572 entries, 0 to 12518
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   job_name       7572 non-null   str
 1   tech_name      7572 non-null   str
 2   base_language  4288 non-null   str
dtypes: str(3)
memory usage: 236.6 KB
None

In [29]:
df_job_skill_prolang = df_job_skill.merge(df_prolang, left_on='tech_name', right_on='prolangname', how='left')
df_job_skill_prolang.rename(columns={'base_language': 'language'}, inplace=True)
df_job_skill_prolang.dropna(subset=['language', 'prolangname'], how='all', inplace=True)
def assign_language(row):
    if pd.notna(row):
        return row.upper()
    else:
        return np.nan
df_job_skill_prolang['new_language'] = df_job_skill_prolang['language'].apply(assign_language)
# 1. Split by the delimiter ' & '
df_job_skill_prolang['new_language'] = df_job_skill_prolang['new_language'].str.split(' & ')
# 2. Explode the list into separate rows
df_job_skill_prolang = df_job_skill_prolang.explode('new_language')
# 3. Clean up any trailing spaces
df_job_skill_prolang['new_language'] = df_job_skill_prolang['new_language'].str.strip()
df_job_prolang = df_job_skill_prolang[['job_name', 'new_language']].copy()
df_job_prolang = df_job_prolang.merge(df_prolang, left_on='new_language', right_on='prolangname', how='left')
df_job_prolang = df_job_prolang.merge(df_job, left_on='job_name', right_on='jobname', how='left')
#df_job_prolang['prolangid'] = df_job_prolang['prolangid'].astype('Int64')
df_job_prolang.drop_duplicates(subset=['jobid', 'prolangid'], keep='first', inplace=True)
df_job_prolang = df_job_prolang[['jobid', 'prolangid']].copy()
print(df_job_prolang.info())
display(df_job_prolang.head())

<class 'pandas.DataFrame'>
Index: 4160 entries, 0 to 5914
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jobid      4160 non-null   int64
 1   prolangid  4160 non-null   int64
dtypes: int64(2)
memory usage: 97.5 KB
None

   jobid  prolangid
0      2         43
1      2         26
2      2         49
5      3         43
6      3         26

In [30]:
df_job_prolang.to_sql('job_prolang', engine, if_exists='append', index=False)

160